import { NgModule } from '@angular/core';

import { MatToolbarModule,
  MatFormFieldModule,
  MatIconModule,
  MatCardModule,
  MatInputModule,
  MatButtonModule,
  MatProgressSpinnerModule,
  MatGridListModule,
  MatSidenavModule,
  MatListModule,
  MatDividerModule,
  MatChipsModule,
  MatMenuModule,
  MatStepperModule,
  MatExpansionModule,
  MatSlideToggleModule,
  MatTabsModule,
  MatButtonToggleModule,
  MatSnackBarModule,
  MatProgressBarModule,
  MatTooltipModule,
  MatSelectModule
} from '@angular/material';

@NgModule({
  imports: [
      MatToolbarModule,
      MatFormFieldModule,
      MatIconModule,
      MatCardModule,
      MatInputModule,
      MatButtonModule,
      MatProgressSpinnerModule,
      MatGridListModule,
      MatSidenavModule,
      MatListModule,
      MatDividerModule,
      MatChipsModule,
      MatMenuModule,
      MatStepperModule,
      MatExpansionModule,
      MatSlideToggleModule,
      MatTabsModule,
      MatButtonToggleModule,
      MatSnackBarModule,
      MatProgressBarModule,
      MatTooltipModule,
      MatSelectModule
  ],
  exports: [
      MatToolbarModule,
      MatFormFieldModule,
      MatIconModule,
      MatCardModule,
      MatInputModule,
      MatButtonModule,
      MatProgressSpinnerModule,
      MatGridListModule,
      MatSidenavModule,
      MatListModule,
      MatDividerModule,
      MatChipsModule,
      MatMenuModule,
      MatStepperModule,
      MatExpansionModule,
      MatSlideToggleModule,
      MatTabsModule,
      MatButtonToggleModule,
      MatSnackBarModule,
      MatProgressBarModule,
      MatTooltipModule,
      MatSelectModule
  ]
})
export class MaterialModule { }
